// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.hzb.lib.user.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserGetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserGetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code user.UserGetRequest}
   */
  public  static final class UserGetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.UserGetRequest)
      UserGetRequestOrBuilder {
    // Use UserGetRequest.newBuilder() to construct.
    private UserGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGetRequest() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserGetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzb.lib.user.proto.UserProto.UserGetRequest.class, com.hzb.lib.user.proto.UserProto.UserGetRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hzb.lib.user.proto.UserProto.UserGetRequest)) {
        return super.equals(obj);
      }
      com.hzb.lib.user.proto.UserProto.UserGetRequest other = (com.hzb.lib.user.proto.UserProto.UserGetRequest) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hzb.lib.user.proto.UserProto.UserGetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UserGetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserGetRequest)
        com.hzb.lib.user.proto.UserProto.UserGetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzb.lib.user.proto.UserProto.UserGetRequest.class, com.hzb.lib.user.proto.UserProto.UserGetRequest.Builder.class);
      }

      // Construct using com.hzb.lib.user.proto.UserProto.UserGetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetRequest_descriptor;
      }

      public com.hzb.lib.user.proto.UserProto.UserGetRequest getDefaultInstanceForType() {
        return com.hzb.lib.user.proto.UserProto.UserGetRequest.getDefaultInstance();
      }

      public com.hzb.lib.user.proto.UserProto.UserGetRequest build() {
        com.hzb.lib.user.proto.UserProto.UserGetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hzb.lib.user.proto.UserProto.UserGetRequest buildPartial() {
        com.hzb.lib.user.proto.UserProto.UserGetRequest result = new com.hzb.lib.user.proto.UserProto.UserGetRequest(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hzb.lib.user.proto.UserProto.UserGetRequest) {
          return mergeFrom((com.hzb.lib.user.proto.UserProto.UserGetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hzb.lib.user.proto.UserProto.UserGetRequest other) {
        if (other == com.hzb.lib.user.proto.UserProto.UserGetRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hzb.lib.user.proto.UserProto.UserGetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hzb.lib.user.proto.UserProto.UserGetRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.UserGetRequest)
    }

    // @@protoc_insertion_point(class_scope:user.UserGetRequest)
    private static final com.hzb.lib.user.proto.UserProto.UserGetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hzb.lib.user.proto.UserProto.UserGetRequest();
    }

    public static com.hzb.lib.user.proto.UserProto.UserGetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGetRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserGetRequest>() {
      public UserGetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserGetRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserGetRequest> getParserForType() {
      return PARSER;
    }

    public com.hzb.lib.user.proto.UserProto.UserGetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserGetReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserGetReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.user.User user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>.user.User user = 1;</code>
     */
    com.hzb.lib.user.proto.UserProto.User getUser();
    /**
     * <code>.user.User user = 1;</code>
     */
    com.hzb.lib.user.proto.UserProto.UserOrBuilder getUserOrBuilder();

    /**
     * <code>.user.Menu menu = 2;</code>
     */
    boolean hasMenu();
    /**
     * <code>.user.Menu menu = 2;</code>
     */
    com.hzb.lib.user.proto.UserProto.Menu getMenu();
    /**
     * <code>.user.Menu menu = 2;</code>
     */
    com.hzb.lib.user.proto.UserProto.MenuOrBuilder getMenuOrBuilder();
  }
  /**
   * Protobuf type {@code user.UserGetReply}
   */
  public  static final class UserGetReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.UserGetReply)
      UserGetReplyOrBuilder {
    // Use UserGetReply.newBuilder() to construct.
    private UserGetReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGetReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserGetReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.hzb.lib.user.proto.UserProto.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.hzb.lib.user.proto.UserProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.hzb.lib.user.proto.UserProto.Menu.Builder subBuilder = null;
              if (menu_ != null) {
                subBuilder = menu_.toBuilder();
              }
              menu_ = input.readMessage(com.hzb.lib.user.proto.UserProto.Menu.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(menu_);
                menu_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzb.lib.user.proto.UserProto.UserGetReply.class, com.hzb.lib.user.proto.UserProto.UserGetReply.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private com.hzb.lib.user.proto.UserProto.User user_;
    /**
     * <code>.user.User user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.user.User user = 1;</code>
     */
    public com.hzb.lib.user.proto.UserProto.User getUser() {
      return user_ == null ? com.hzb.lib.user.proto.UserProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.user.User user = 1;</code>
     */
    public com.hzb.lib.user.proto.UserProto.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MENU_FIELD_NUMBER = 2;
    private com.hzb.lib.user.proto.UserProto.Menu menu_;
    /**
     * <code>.user.Menu menu = 2;</code>
     */
    public boolean hasMenu() {
      return menu_ != null;
    }
    /**
     * <code>.user.Menu menu = 2;</code>
     */
    public com.hzb.lib.user.proto.UserProto.Menu getMenu() {
      return menu_ == null ? com.hzb.lib.user.proto.UserProto.Menu.getDefaultInstance() : menu_;
    }
    /**
     * <code>.user.Menu menu = 2;</code>
     */
    public com.hzb.lib.user.proto.UserProto.MenuOrBuilder getMenuOrBuilder() {
      return getMenu();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (menu_ != null) {
        output.writeMessage(2, getMenu());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (menu_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMenu());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hzb.lib.user.proto.UserProto.UserGetReply)) {
        return super.equals(obj);
      }
      com.hzb.lib.user.proto.UserProto.UserGetReply other = (com.hzb.lib.user.proto.UserProto.UserGetReply) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasMenu() == other.hasMenu());
      if (hasMenu()) {
        result = result && getMenu()
            .equals(other.getMenu());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasMenu()) {
        hash = (37 * hash) + MENU_FIELD_NUMBER;
        hash = (53 * hash) + getMenu().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.UserGetReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hzb.lib.user.proto.UserProto.UserGetReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UserGetReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserGetReply)
        com.hzb.lib.user.proto.UserProto.UserGetReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzb.lib.user.proto.UserProto.UserGetReply.class, com.hzb.lib.user.proto.UserProto.UserGetReply.Builder.class);
      }

      // Construct using com.hzb.lib.user.proto.UserProto.UserGetReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (menuBuilder_ == null) {
          menu_ = null;
        } else {
          menu_ = null;
          menuBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_UserGetReply_descriptor;
      }

      public com.hzb.lib.user.proto.UserProto.UserGetReply getDefaultInstanceForType() {
        return com.hzb.lib.user.proto.UserProto.UserGetReply.getDefaultInstance();
      }

      public com.hzb.lib.user.proto.UserProto.UserGetReply build() {
        com.hzb.lib.user.proto.UserProto.UserGetReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hzb.lib.user.proto.UserProto.UserGetReply buildPartial() {
        com.hzb.lib.user.proto.UserProto.UserGetReply result = new com.hzb.lib.user.proto.UserProto.UserGetReply(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (menuBuilder_ == null) {
          result.menu_ = menu_;
        } else {
          result.menu_ = menuBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hzb.lib.user.proto.UserProto.UserGetReply) {
          return mergeFrom((com.hzb.lib.user.proto.UserProto.UserGetReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hzb.lib.user.proto.UserProto.UserGetReply other) {
        if (other == com.hzb.lib.user.proto.UserProto.UserGetReply.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasMenu()) {
          mergeMenu(other.getMenu());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hzb.lib.user.proto.UserProto.UserGetReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hzb.lib.user.proto.UserProto.UserGetReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.hzb.lib.user.proto.UserProto.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hzb.lib.user.proto.UserProto.User, com.hzb.lib.user.proto.UserProto.User.Builder, com.hzb.lib.user.proto.UserProto.UserOrBuilder> userBuilder_;
      /**
       * <code>.user.User user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public com.hzb.lib.user.proto.UserProto.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.hzb.lib.user.proto.UserProto.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public Builder setUser(com.hzb.lib.user.proto.UserProto.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public Builder setUser(
          com.hzb.lib.user.proto.UserProto.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public Builder mergeUser(com.hzb.lib.user.proto.UserProto.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.hzb.lib.user.proto.UserProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public com.hzb.lib.user.proto.UserProto.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      public com.hzb.lib.user.proto.UserProto.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.hzb.lib.user.proto.UserProto.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.user.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hzb.lib.user.proto.UserProto.User, com.hzb.lib.user.proto.UserProto.User.Builder, com.hzb.lib.user.proto.UserProto.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hzb.lib.user.proto.UserProto.User, com.hzb.lib.user.proto.UserProto.User.Builder, com.hzb.lib.user.proto.UserProto.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private com.hzb.lib.user.proto.UserProto.Menu menu_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hzb.lib.user.proto.UserProto.Menu, com.hzb.lib.user.proto.UserProto.Menu.Builder, com.hzb.lib.user.proto.UserProto.MenuOrBuilder> menuBuilder_;
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public boolean hasMenu() {
        return menuBuilder_ != null || menu_ != null;
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public com.hzb.lib.user.proto.UserProto.Menu getMenu() {
        if (menuBuilder_ == null) {
          return menu_ == null ? com.hzb.lib.user.proto.UserProto.Menu.getDefaultInstance() : menu_;
        } else {
          return menuBuilder_.getMessage();
        }
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public Builder setMenu(com.hzb.lib.user.proto.UserProto.Menu value) {
        if (menuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          menu_ = value;
          onChanged();
        } else {
          menuBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public Builder setMenu(
          com.hzb.lib.user.proto.UserProto.Menu.Builder builderForValue) {
        if (menuBuilder_ == null) {
          menu_ = builderForValue.build();
          onChanged();
        } else {
          menuBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public Builder mergeMenu(com.hzb.lib.user.proto.UserProto.Menu value) {
        if (menuBuilder_ == null) {
          if (menu_ != null) {
            menu_ =
              com.hzb.lib.user.proto.UserProto.Menu.newBuilder(menu_).mergeFrom(value).buildPartial();
          } else {
            menu_ = value;
          }
          onChanged();
        } else {
          menuBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public Builder clearMenu() {
        if (menuBuilder_ == null) {
          menu_ = null;
          onChanged();
        } else {
          menu_ = null;
          menuBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public com.hzb.lib.user.proto.UserProto.Menu.Builder getMenuBuilder() {
        
        onChanged();
        return getMenuFieldBuilder().getBuilder();
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      public com.hzb.lib.user.proto.UserProto.MenuOrBuilder getMenuOrBuilder() {
        if (menuBuilder_ != null) {
          return menuBuilder_.getMessageOrBuilder();
        } else {
          return menu_ == null ?
              com.hzb.lib.user.proto.UserProto.Menu.getDefaultInstance() : menu_;
        }
      }
      /**
       * <code>.user.Menu menu = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hzb.lib.user.proto.UserProto.Menu, com.hzb.lib.user.proto.UserProto.Menu.Builder, com.hzb.lib.user.proto.UserProto.MenuOrBuilder> 
          getMenuFieldBuilder() {
        if (menuBuilder_ == null) {
          menuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hzb.lib.user.proto.UserProto.Menu, com.hzb.lib.user.proto.UserProto.Menu.Builder, com.hzb.lib.user.proto.UserProto.MenuOrBuilder>(
                  getMenu(),
                  getParentForChildren(),
                  isClean());
          menu_ = null;
        }
        return menuBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.UserGetReply)
    }

    // @@protoc_insertion_point(class_scope:user.UserGetReply)
    private static final com.hzb.lib.user.proto.UserProto.UserGetReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hzb.lib.user.proto.UserProto.UserGetReply();
    }

    public static com.hzb.lib.user.proto.UserProto.UserGetReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGetReply>
        PARSER = new com.google.protobuf.AbstractParser<UserGetReply>() {
      public UserGetReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserGetReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGetReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserGetReply> getParserForType() {
      return PARSER;
    }

    public com.hzb.lib.user.proto.UserProto.UserGetReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code user.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userId_ = 0L;
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readSInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzb.lib.user.proto.UserProto.User.class, com.hzb.lib.user.proto.UserProto.User.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>sint64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeSInt64(1, userId_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, userId_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hzb.lib.user.proto.UserProto.User)) {
        return super.equals(obj);
      }
      com.hzb.lib.user.proto.UserProto.User other = (com.hzb.lib.user.proto.UserProto.User) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getPassword()
          .equals(other.getPassword());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hzb.lib.user.proto.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.User)
        com.hzb.lib.user.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzb.lib.user.proto.UserProto.User.class, com.hzb.lib.user.proto.UserProto.User.Builder.class);
      }

      // Construct using com.hzb.lib.user.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_User_descriptor;
      }

      public com.hzb.lib.user.proto.UserProto.User getDefaultInstanceForType() {
        return com.hzb.lib.user.proto.UserProto.User.getDefaultInstance();
      }

      public com.hzb.lib.user.proto.UserProto.User build() {
        com.hzb.lib.user.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hzb.lib.user.proto.UserProto.User buildPartial() {
        com.hzb.lib.user.proto.UserProto.User result = new com.hzb.lib.user.proto.UserProto.User(this);
        result.userId_ = userId_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hzb.lib.user.proto.UserProto.User) {
          return mergeFrom((com.hzb.lib.user.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hzb.lib.user.proto.UserProto.User other) {
        if (other == com.hzb.lib.user.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hzb.lib.user.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hzb.lib.user.proto.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>sint64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>sint64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.User)
    }

    // @@protoc_insertion_point(class_scope:user.User)
    private static final com.hzb.lib.user.proto.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hzb.lib.user.proto.UserProto.User();
    }

    public static com.hzb.lib.user.proto.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.hzb.lib.user.proto.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MenuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.Menu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string perms = 1;</code>
     */
    java.lang.String getPerms();
    /**
     * <code>string perms = 1;</code>
     */
    com.google.protobuf.ByteString
        getPermsBytes();
  }
  /**
   * Protobuf type {@code user.Menu}
   */
  public  static final class Menu extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.Menu)
      MenuOrBuilder {
    // Use Menu.newBuilder() to construct.
    private Menu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Menu() {
      perms_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Menu(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              perms_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_Menu_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzb.lib.user.proto.UserProto.internal_static_user_Menu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzb.lib.user.proto.UserProto.Menu.class, com.hzb.lib.user.proto.UserProto.Menu.Builder.class);
    }

    public static final int PERMS_FIELD_NUMBER = 1;
    private volatile java.lang.Object perms_;
    /**
     * <code>string perms = 1;</code>
     */
    public java.lang.String getPerms() {
      java.lang.Object ref = perms_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        perms_ = s;
        return s;
      }
    }
    /**
     * <code>string perms = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPermsBytes() {
      java.lang.Object ref = perms_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        perms_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPermsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, perms_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPermsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, perms_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hzb.lib.user.proto.UserProto.Menu)) {
        return super.equals(obj);
      }
      com.hzb.lib.user.proto.UserProto.Menu other = (com.hzb.lib.user.proto.UserProto.Menu) obj;

      boolean result = true;
      result = result && getPerms()
          .equals(other.getPerms());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERMS_FIELD_NUMBER;
      hash = (53 * hash) + getPerms().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hzb.lib.user.proto.UserProto.Menu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hzb.lib.user.proto.UserProto.Menu prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.Menu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.Menu)
        com.hzb.lib.user.proto.UserProto.MenuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_Menu_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_Menu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzb.lib.user.proto.UserProto.Menu.class, com.hzb.lib.user.proto.UserProto.Menu.Builder.class);
      }

      // Construct using com.hzb.lib.user.proto.UserProto.Menu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        perms_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hzb.lib.user.proto.UserProto.internal_static_user_Menu_descriptor;
      }

      public com.hzb.lib.user.proto.UserProto.Menu getDefaultInstanceForType() {
        return com.hzb.lib.user.proto.UserProto.Menu.getDefaultInstance();
      }

      public com.hzb.lib.user.proto.UserProto.Menu build() {
        com.hzb.lib.user.proto.UserProto.Menu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hzb.lib.user.proto.UserProto.Menu buildPartial() {
        com.hzb.lib.user.proto.UserProto.Menu result = new com.hzb.lib.user.proto.UserProto.Menu(this);
        result.perms_ = perms_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hzb.lib.user.proto.UserProto.Menu) {
          return mergeFrom((com.hzb.lib.user.proto.UserProto.Menu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hzb.lib.user.proto.UserProto.Menu other) {
        if (other == com.hzb.lib.user.proto.UserProto.Menu.getDefaultInstance()) return this;
        if (!other.getPerms().isEmpty()) {
          perms_ = other.perms_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hzb.lib.user.proto.UserProto.Menu parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hzb.lib.user.proto.UserProto.Menu) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object perms_ = "";
      /**
       * <code>string perms = 1;</code>
       */
      public java.lang.String getPerms() {
        java.lang.Object ref = perms_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          perms_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string perms = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPermsBytes() {
        java.lang.Object ref = perms_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          perms_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string perms = 1;</code>
       */
      public Builder setPerms(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        perms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string perms = 1;</code>
       */
      public Builder clearPerms() {
        
        perms_ = getDefaultInstance().getPerms();
        onChanged();
        return this;
      }
      /**
       * <code>string perms = 1;</code>
       */
      public Builder setPermsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        perms_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.Menu)
    }

    // @@protoc_insertion_point(class_scope:user.Menu)
    private static final com.hzb.lib.user.proto.UserProto.Menu DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hzb.lib.user.proto.UserProto.Menu();
    }

    public static com.hzb.lib.user.proto.UserProto.Menu getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Menu>
        PARSER = new com.google.protobuf.AbstractParser<Menu>() {
      public Menu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Menu(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Menu> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Menu> getParserForType() {
      return PARSER;
    }

    public com.hzb.lib.user.proto.UserProto.Menu getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserGetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserGetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserGetReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserGetReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Menu_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_Menu_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userservice.proto\022\004user\"\036\n\016UserGetRequ" +
      "est\022\014\n\004name\030\001 \001(\t\"B\n\014UserGetReply\022\030\n\004use" +
      "r\030\001 \001(\0132\n.user.User\022\030\n\004menu\030\002 \001(\0132\n.user" +
      ".Menu\"(\n\004User\022\016\n\006userId\030\001 \001(\022\022\020\n\010passwor" +
      "d\030\002 \001(\t\"\025\n\004Menu\022\r\n\005perms\030\001 \001(\t2M\n\013UserSe" +
      "rvice\022>\n\020getUserInfoPerms\022\024.user.UserGet" +
      "Request\032\022.user.UserGetReply\"\000B%\n\026com.hzb" +
      ".lib.user.protoB\tUserProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_UserGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_UserGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserGetRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_user_UserGetReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserGetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserGetReply_descriptor,
        new java.lang.String[] { "User", "Menu", });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "UserId", "Password", });
    internal_static_user_Menu_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_Menu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_Menu_descriptor,
        new java.lang.String[] { "Perms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
