grpc:
  server:
    port: 9098
spring:
  cloud:
    nacos:
      server-addr: 119.3.171.130:8848
      discovery:
        group: mushanimg-project
        namespace: dev
  application:
    name: system-service