server:
  port: 8088
spring:
  cloud:
    nacos:
      server-addr: 119.3.171.130:8848
      discovery:
        group: mushanimg-project
        namespace: dev
  application:
    name: grpc-client
grpc:
  client:
    system-service:
      negotiation-type: plaintext